config/routes.rb
Rails.application.routes.draw do
  resources :rides

  resources :locations

  devise_for :users

  root 'rides#index'

end

app/models/ride.rb
class Ride < ActiveRecord::Base
end

app/controllers/rides_controller.rb
require 'pry'
require 'pry-nav'
require 'util'
require 'geocoder'
class RidesController < ApplicationController
  before_action :set_ride, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json

  def index
    @rides = Ride.all

    @all_rides = Array.new
    @rides.each do |ride|
      @rider_objects = Array.new
      arr = Array.new
      @rider_objects = convert_to_obj_arr(arr,@rider_objects, ride.travelers)
      @all_rides.push(@rider_objects)
    end
    respond_with(@rides,@all_rides)
  end

  def show
    arr =  @ride.travelers.split(%r{,\s*})
    @rider_objects = Array.new
    @rider_objects = convert_to_obj_arr(arr,@rider_objects,@ride.travelers)

    coords = []
    @rider_objects.each do |rider|
      coord = [rider.latitude, rider.longitude]
      coords.push(coord)
    end
    address = @ride.address
    # binding.pry
    @dest_coords = Geocoder.coordinates(address)
    ret = all_the_things(coords)
    ret = sort_the_sources(ret,@dest_coords)
    @minPath = ret
    coord_list = Array.new
    @minPath.each do |cluster|
      cluster.values.each do |coord|
        coord_list.push(coord)
      end
    end
    @coord_list = coord_list

    respond_with(@ride,@rider_objects, @minPath,@coord_list, @dest_coords )
  end

  def new
    @ride = Ride.new
    respond_with(@ride)
  end

  def edit
  end

  def create
    @ride = Ride.new(ride_params)
    @address = @ride.address
    @ride.travelers = @ride.travelers + ",#{current_user.username}"
    arr = @ride.travelers.split(%r{,\s*})
    @rider_objects = convert_to_obj_arr_redo(arr)
    @ride.save
    respond_with(@ride)
  end



  def update
    @ride.update(ride_params)
    respond_with(@ride)
  end

  def destroy
    @ride.destroy
    respond_with(@ride)
  end

  private
    def set_ride
      @ride = Ride.find(params[:id])
    end

    def ride_params
      params.require(:ride).permit(:address, :travelers)
    end

    def convert_to_obj_arr(arr,rider_obj, travelers)

      listOfTravelers = travelers.split(%r{,\s*})
      for rider in listOfTravelers
        some_obj = User.find_by username: rider
        puts some_obj
        if some_obj != nil
          rider_obj.push(some_obj)
        end
      end
      return rider_obj
    end

    def convert_to_obj_arr_redo(arr)
      rider_obj = []
      for rider in arr
        some_obj = User.find_by username: rider
        puts some_obj
        if some_obj != nil
          rider_obj.push(some_obj)
        end
      end
      return rider_obj
    end
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/views/rides/_form.html.erb
<%= simple_form_for(@ride,  html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :address ,:required => true %>
    <%= f.input :travelers , :required => true%>
  </div>

  <div class="form-actions">
    <button class="btn btn-success"> <%= f.button :submit%> </button>
  </div>
<% end %>

app/views/rides/edit.html.erb
<div class="container" id="show_graph">
    <h1>Editing ride</h1>

    <%= render 'form' , :style => "width: 50%"%>

    <%= link_to 'Show', @ride,id: 'edit_graph' , class: "btn btn-default", type: 'button', tag: 'button' %>
    <%= link_to 'Back', rides_path,id: 'edit_graph' , class: "btn btn-default", type: 'button', tag: 'button' %>
</div>

app/views/rides/index.html.erb
<div class="container" id="rideInput">
  <h1>Hello <%= current_user.username %></h1>

    <% found = false %>
    <% userRide = nil %>
    <% if @all_rides.length == 0 %>
      <h2>Where will you be traveling today?</h2>
        <%= simple_form_for(Ride.new) do |f| %>
            <%= f.error_notification %>

            <div class="form-inputs">
              <%= f.input :address, :required => true,:label => "Address (Location,City,State)" %>
              <%= f.input :travelers , :required => true, :label => "Travelers (comma seperated)"%>
            </div>

            <div class="form-actions">
              <%= f.button :submit %>
            </div>
        <% end %>
      <% end %>
    <% @all_rides.each do |ride| %>
        <% if ride.include? current_user %>
            <% found = true %>
            <% userRide = ride %>
            <% break %>
        <% else %>
          <h2>Where will you be traveling today?</h2>
            <%= simple_form_for(Ride.new ,html: { class: 'form-horizontal' }) do |f| %>
                <%= f.error_notification %>

                <div class="form-inputs">
                  <%= f.input :address, :required => true ,:label => "Address (Location,City,State)"%>
                  <%= f.input :travelers , :required => true, :label => "Travelers (comma seperated)"%>
                </div>

                <div class="form-actions">
                  <%= f.button :submit %>
                </div>
            <% end %>
        <%end%>
    <%end%>

  <% party = 0 %>

  <tbody style="border: double">
    <% if found %>
      <h2>It looks like you are part of a party already. Hit show to see more details!</h2>
    <%end%>

    <% @rides.each do |ride| %>
          <% if ride.travelers.include? current_user.username %>
          <div class="list-group" style="margin-bottom: 0px;margin: auto;width: 25%;">
            <div class="list-group-item"> Address: <%= ride.address %> </div>
            <div class="list-group-item">Party members: <%= ride.travelers %> </div>
            </div>
              <div class="btn-group" role="group">
                 <%= link_to 'Show', ride, id: 'edit_graph' , class: "btn btn-success", type: 'button', tag: 'button'%>
                <%= link_to 'Edit', edit_ride_path(ride),class: "btn btn-info", type: 'button', tag: 'button',id: 'edit_graph' %>
                <%= link_to 'Destroy', ride, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", type: 'button', tag: 'button', id: 'edit_graph'%>
              </div>
               <br>
          <%end%>
            <br>
    <% end %>
    </tbody>
</div>


    <!--<% @rides.each do |ride| %>-->
      <!--<tr>-->
        <!--<td><%= ride.address %></td>-->
        <!--<td><%= ride.travelers %></td>-->
        <!--<td><%= link_to 'Show', ride %></td>-->
        <!--<td><%= link_to 'Edit', edit_ride_path(ride) %></td>-->
        <!--<td><%= link_to 'Destroy', ride, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      <!--</tr>-->
    <!--<% end %>-->
  <!--</tbody>-->
<!--</table>-->

<!--<br>-->

<!--<%= link_to 'New Ride', new_ride_path %>-->

app/views/rides/new.html.erb
<h1>New ride</h1>

<%= render 'form' %>

<%= link_to 'Back', rides_path %>

app/views/rides/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container" id="show_graph">
  <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Address </h3>
        </div>
        <div class="panel-body">
            <%= @ride.address %>
        </div>
  </div>

  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title">Travelers </h3>
    </div>
    <div class="panel-body">
      <%= @ride.travelers %>
    </div>
  </div>

  <!--<p>Clusters are:</p>-->

  <%= link_to 'Edit', edit_ride_path(@ride), id: 'edit_graph' , class: "btn btn-info", type: 'button', tag: 'button' %>
  <%= link_to 'Back', rides_path, id: 'edit_graph' , class: "btn btn-warning", type: 'button', tag: 'button' %>
  <script type="text/javascript">
      function initialize() {
          var coordList = '<%= @coord_list %>';
          var address = '<%= @dest_coords %>';
          address = JSON.parse(address);
          coordList = JSON.parse(coordList);
          var newCoordList = [];
          //linearizes the 2D array
          for (list in coordList) {
              for (cluster in coordList[list]) {
                  newCoordList.push(coordList[list][cluster]);
              }
          }

          var myLatlng = new google.maps.LatLng(address[0],address[1]);
          var mapOptions = {
              zoom: 12,
              center: myLatlng
          };
          var marker = new google.maps.Marker({
              position: myLatlng,
              title:"Drag me!",
              draggable: true
          });
          markers =[];
          var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

          marker.setMap(map);
          var colors = ['#42FF23','#FF0000','#FFF8000','0000FF'];
          for (clusterIdx in coordList) {
              var colorIdx = clusterIdx%4;
              var temp = [];
              for (coordIdx in coordList[clusterIdx]) {
                  var aPoint = new google.maps.LatLng(coordList[clusterIdx][coordIdx][0],coordList[clusterIdx][coordIdx][1]);
                  var aMarker = new google.maps.Marker({
                      position: aPoint,
                      map: map,
                      draggable: true
                  });
                  aMarker.setMap(map);
                  temp.push(aPoint);
              }
              temp.push(myLatlng); //final end point of every cluster
//            console.log(temp);

              var path = new google.maps.Polyline( {
                  path: temp,
                  geodesic: true,
                  strokeColor: colors[colorIdx],
                  strokeOpacity: 1.0,
                  strokeWeight: 3
              });
              path.setMap(map);
          }
      }
      google.maps.event.addDomListener(window, 'load', initialize);

  </script>
  <div style="height:40em; margin: 0px;padding: 0px;width: 100%;">
    <div id="map-canvas" style="height:100%; width:100%;"></div>

  </div>

</div>